# Generated by Django 4.1.8 on 2023-04-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='kentsam262@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
